In [1]:
import cv2
import pykep
import numpy as np
import imutils
import math

Image tools

In [2]:
def debris_in_pixels(physical_size, distance, alpha=np.pi/6, beta=np.pi/6, dimensions = (1080, 1980)):
    """
    Returns how many pixels the object at a given distance should take up
    :param physical_size: The size of the object
    :param distance: Distance between the target and observer
    :param alpha: horizontal FOV. Radians
    :param beta: vertical FOV. Radians
    :param dimensions: the pixel dimensions of the observer camera used
    """
    
    len_x = 2*np.tan(alpha)*distance
    len_y = 2*np.tan(beta)*distance
    
    px_per_length_cols =  dimensions[0]/len_x
    px_per_length_rows =  dimensions[1]/len_y
    new_shape = (math.ceil(physical_size[0] * px_per_length_rows), math.ceil(physical_size[1] * px_per_length_cols))
    # think about the rounding here
    return new_shape


def resize(original_image, physical_size, distance):
    """
    Resize the image based on the physical size of the target object and the relative distance between 
    target object and observer
    :param physical_size: The size of the object in km
    :param distance: Distance between the target and observer planes, the z coordinate of the relative vector
    """
    height, width = debris_in_pixels(physical_size, distance)
    if width == 0 and height ==0:
        return False  # can't resize, object too small
    else:
        return cv2.resize(original_image, (width, height), interpolation=cv2.INTER_AREA)

In [3]:
def roi_in_frame(left_corner, object_size, frame):
    """
    Return the part of the ROI that is in the frame.
    :left_corner: the coordinates of the left corner of the object in px.
    :object_size: size of the object in pixels in CV2 coordinates (columns, rows)
    """
    frame_size = frame.shape
    ROI = [[left_corner[0], left_corner[0] + object_size[0]],[left_corner[1], left_corner[1] + object_size[1]]]
    
    if left_corner[1] + object_size[1] > frame_size[1]:
        print("outside the right bounding edge")
        # outside the right bounding edge
        ROI[1] = [left_corner[1], frame_size[1]]
    if left_corner[1] < 0:
        print("outside the left bounding edge")
        # outside the left bounding edge
        ROI[1] = [0, left_corner[1] + object_size[1]]

    if left_corner[0] + object_size[0] > frame_size[0]:
        print("outside the bottom bounding edge")
        # outside the bottom bounding edge
        ROI[0] = [left_corner[0], frame_size[0]]
    if left_corner[0] < 0:
        print("outside the upper bounding edge")
        # outside the upper bounding edge
        ROI[0] = [0, left_corner[0] + object_size[0]]

    return frame[ROI[0][0]:ROI[0][1], ROI[1][0]:ROI[1][1]]


def obj_in_frame(left_corner, frame, img):
    image_size = img.shape
    frame_size = frame.shape
    ROI = [[0,image_size[0]],[0,image_size[1]]]  # the whole image of the object
    if left_corner[1] + image_size[1] > frame_size[1]:
        # outside the right bounding edge
        ROI[1] = [0, frame_size[1] - left_corner[1]]
    if left_corner[1] < 0:
        # outside the left bounding edge
        ROI[1] = [-left_corner[1], image_size[1]]

    if left_corner[0] + image_size[0] > frame_size[0]:
        # outside the bottom bounding edge
        ROI[0] = [0, frame_size[0] - left_corner[0]]
    if left_corner[0] < 0:
        # outside the upper bounding edge
        ROI[0] = [-left_corner[0], image_size[0]]

    return img[ROI[0][0]:ROI[0][1], ROI[1][0]:ROI[1][1]] 

In [4]:
def create_mask(img):
    return np.zeros(img.shape[:2], dtype="uint8")

Orbital Mechanics

In [5]:
def propagate_based_on_vector(r,v, t):
    rf, vf = pykep.propagate_lagrangian(r0 = r, v0 = v, tof = t,mu = 398600)
    return np.array(rf), np.array(vf)

def propagate_based_on_elements(elements, t, kepler=True):
    r, v = pykep.par2ic(elements, mu=398600)
    rf,vf = pykep.propagate_lagrangian(r0 = r, v0 = v, tof = t,mu = 398600)
    if kepler == False:  # return vectors
        return np.array(rf),np.array(vf)
    if kepler == True:  # return kepler elements
        return pykep.ic2par(rf,vf,mu = 398600)

Utility

In [6]:
def delete_white_background(img, write=False):
    """
    Takes the images of Debris that I made in paint.
    Inverts the colours and deletes the white background.
    """
    img = np.invert(img)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    _, alpha = cv2.threshold(gray, 240, 255, cv2.THRESH_BINARY)
    
    # Using cv2.split() to split channels 
    # of coloured image
    b, g, r = cv2.split(img)

    # Making list of Red, Green, Blue
    # Channels and alpha
    rgba = [b,g,r, alpha]

    # Using cv2.merge() to merge rgba
    # into a coloured/multi-channeled image
    dst = cv2.merge(rgba,3)
    print("dst shape", dst.shape)

    # Writing and saving to a new image
    if write is True:
        cv2.imwrite("debris/deb.png", dst)
    return dst        

FOV

In [7]:
# Checks if a matrix is a valid rotation matrix.
def isRotationMatrix(R) :
    Rt = np.transpose(R)
    shouldBeIdentity = np.dot(Rt, R)
    I = np.identity(3, dtype = R.dtype)
    n = np.linalg.norm(I - shouldBeIdentity)
    return n < 1e-6
 
# Calculates rotation matrix to euler angles
# The result is the same as MATLAB except the order
# of the euler angles ( x and z are swapped ).
def rotationMatrixToEulerAngles(R) :
 
    assert(isRotationMatrix(R))
 
    sy = math.sqrt(R[0,0] * R[0,0] +  R[1,0] * R[1,0])
 
    singular = sy < 1e-6
 
    if  not singular :
        x = math.atan2(R[2,1] , R[2,2])
        y = math.atan2(-R[2,0], sy)
        z = math.atan2(R[1,0], R[0,0])
    else :
        x = math.atan2(-R[1,2], R[1,1])
        y = math.atan2(-R[2,0], sy)
        z = 0
 
    return np.array([x, y, z])

In [8]:
def to_body_axis(vector, r, v):
    """
    Calculates the rotation matrix and applies it. Returns the converted vector.
    r and v are used to calculate the rotation matrix and vector is the vector to be 
    rotated.
    """
    unit_r = r/np.linalg.norm(r)
    unit_v = v/np.linalg.norm(v)

    R = np.array([[unit_v[0], -unit_r[0], unit_r[1]*unit_v[2] - unit_v[1]*unit_r[2]],
                [unit_v[1], -unit_r[1], unit_v[0]*unit_r[2] - unit_r[0]*unit_v[2]],
                [unit_v[2], -unit_r[2], unit_r[0]*unit_v[1] - unit_v[0]*unit_r[1]]])
    R = R.transpose()
    
    return R.dot(vector)

In [48]:
vec = [1,0,0]
r = [0,0,1]
v = [0,1,0]
to_body_axis(vec, r, v)

array([ 0.,  0., -1.])

In [9]:
def angle_between(r1,r2):
    """
    Calculate the angle between two vectors
    """
    unit_1 = r1/np.linalg.norm(r1)
    unit_2 = r2/np.linalg.norm(r2)
    return np.arccos(np.dot(unit_1,unit_2))

def behind_earth(r1, r2, R=6371):
    """
    Checks if the target is between the Earth and observer based on 
    a line segment intersecting the sphere.
    Returns true if the target is behind the Earth.
    :param r1: observer
    :param r2: target
    """
    if angle_between(r1,r2) < np.pi/2:  
        return False  # does not intersect
    
    phi = np.arccos(np.dot(r1, r2-r1)/(np.linalg.norm(r1)*np.linalg.norm(r2-r1)))
    H = np.linalg.norm(r1)*np.sin(phi)
    
    if H <= R:
        return True  # intersects
    if H > R:
        return False  # does not intersect

def in_FOV(r1, v1, r2, max_vertical=np.radians(30), max_horisontal=np.radians(30)):
    """
    Checks if the observer should be able to see the target.
    1 for observer. 2 for target.
    Returns True if yes
    """

    rel = r2 - r1
    
    if behind_earth(r1,r2) is True:
        print("failed cause earth")
        return False
    
    rel_unit = (rel)/np.linalg.norm(rel)
    print("relative in global", rel_unit)
    rel_unit = to_body_axis(rel_unit, r1, v1) 
    print("relative in body", rel_unit)
    if rel_unit[1] < 0:
        print("failed cause y")
        return False

    horisontal_angle = abs(np.arctan(rel_unit[0]/rel_unit[1]))  # in the xy plane 
    vertical_angle = abs(np.arctan(rel_unit[2]/rel_unit[1]))  # in yz plane
    print("angles", np.degrees(horisontal_angle),np.degrees(vertical_angle))
    if horisontal_angle <= max_horisontal and vertical_angle <= max_vertical:
        return True
    else:
        print("failed cause angles")
        return False

In [10]:
r1 = np.array([7300,0,0])
r2 = np.array([7200,0,0])
behind_earth(r1, r2)

False

In [10]:
def get_distance(r1, v1, r2):
    rel = r2 - r1
    rel = to_body_axis(rel, r1, v1)
    distance = rel[1]  # y axis is pointed towards Earth
    return distance

def to_pixels(r,distance, shape, cols=1980, rows=1080, alpha=np.pi/6, beta=np.pi/6,):
    """
    Converts physical location to pixels and pixel coordinates. Returns rows, columns
    """
    len_x = 2*np.tan(alpha)*distance
    len_z = 2*np.tan(beta)*distance
    px_per_length_cols =  cols/len_x
    px_per_length_rows =  rows/len_z
    return math.ceil(-r[0]*px_per_length_rows+rows/2-shape[0]/2), math.ceil(r[2]*px_per_length_cols+cols/2-shape[1]/2)


Initialisation

In [11]:
elements_sat = [7350,0.0,np.radians(0),np.radians(0),np.radians(0),np.radians(0)]
elements_deb = [7133.8,0.0043,np.radians(10),np.radians(0),np.radians(0),np.radians(0)]

In [12]:
rO, vO = np.array(pykep.par2ic(elements_sat))
rT, vT = np.array(pykep.par2ic(elements_deb))
for t in range(10):
    r1,v1 = propagate_based_on_elements(elements_sat, t, kepler=False)
    r2 = propagate_based_on_elements(elements_deb, t, kepler=False)[0]
    print(to_body_axis(r2-r1, r1,v1))
    #print(r2)
    print("---------------------------")

[  0.      246.87534   0.     ]
---------------------------
[  0.27627132 246.87544801   1.30360438]
---------------------------
[  0.55254304 246.87577204   2.6072073 ]
---------------------------
[  0.82881556 246.87631208   3.91080733]
---------------------------
[  1.1050893  246.87706814   5.21440301]
---------------------------
[  1.38136465 246.87804022   6.51799288]
---------------------------
[  1.65764201 246.87922829   7.82157551]
---------------------------
[  1.93392179 246.88063238   9.12514944]
---------------------------
[  2.21020439 246.88225245  10.42871322]
---------------------------
[  2.48649021 246.88408852  11.7322654 ]
---------------------------


In [18]:
vs = "Earth/test.avi"
img_path = "debris\deb1.png"

In [26]:
object_og = cv2.imread(img_path)
object_og = np.invert(object_og)  # get white object

In [ ]:
object_og = cv2.imread(img_path)
#print(object_og.shape)
#object_og = delete_white_background(object_og, write=False)
#print(object_og.shape)
distance = 7000
object_resized = resize(object_og, (500,500), distance)
cv2.imshow("resized", object_resized)
cv2.waitKey(0)

In [30]:
cap = cv2.VideoCapture(vs)  # open the video file
frame_width = int(cap.get(3))
frame_height = int(cap.get(4))
out = cv2.VideoWriter('Earth_ball.avi', cv2.VideoWriter_fourcc('M', 'J', 'P', 'G'), 30, (frame_width, frame_height))
t = 0
if cap.isOpened() is False:
    print("Error opening video file")

Body

In [31]:
while cap.isOpened():
    ret0, frame = cap.read()
    print(ret0)
    if ret0 is True:
        rO, vO = propagate_based_on_elements(elements_sat, t, kepler=False)
        rT, vT = propagate_based_on_elements(elements_deb, t, kepler=False)
        t+=1  # move ahead by one second
        if in_FOV(rO, vO, rT) is True:
            rel = rT - rO
            distance = np.linalg.norm(rel)
            #print("distance", distance)
            object_resized = resize(object_og, (10,10), distance)  # size of target in pixels
            if object_resized is not False:
                rel = to_body_axis(rel, rO, vO)
                rT = to_body_axis(rT,rO, vO)
                #print("relative vector", rel)
                left_corner = to_pixels(rel, distance,object_resized.shape)  # location of target in the frame
                #print("left corner", left_corner)
                #print("object resized", object_resized.shape)
                roi = roi_in_frame(left_corner, object_resized.shape, frame)
                #print("roi shape", roi.shape)
                # create mask and inverse mask
                object_in_frame = obj_in_frame(left_corner,frame,object_resized)
                #cv2.imshow("object in frame", object_in_frame)
                gray = cv2.cvtColor(object_in_frame, cv2.COLOR_BGR2GRAY)
                ret, mask = cv2.threshold(gray, 10, 255, cv2.THRESH_BINARY)
                mask_inv = cv2.bitwise_not(mask)
                #print("mask shape", mask.shape)
                #cv2.imshow("mask", mask)
                #cv2.imshow("inverse mask", mask_inv)
                # black out the area of object in ROI
                frame_bg = cv2.bitwise_and(roi, roi, mask=mask_inv)
                object_fg = cv2.bitwise_and(object_in_frame, object_in_frame, mask=mask)
                #print("object_fg", object_fg.shape)
                #print("frame_bg", frame_bg.shape)
                #cv2.imshow("frame background", frame_bg)
                #cv2.imshow("object foreground", object_fg)
                dst = cv2.add(frame_bg, object_fg)
                #cv2.imshow("dst", dst)
                frame[left_corner[0]:roi.shape[0]+left_corner[0],left_corner[1]:roi.shape[1]+left_corner[1]] = dst
                
                #cv2.imshow("Earth with ball", frame)
                #cv2.waitKey(0)
        out.write(frame)
    else:
        break

out.release()
cap.release()
cv2.destroyAllWindows()

True
relative in global [-1.  0.  0.]
relative in body [0. 1. 0.]
angles 0.0 0.0
True
relative in global [-9.99986052e-01  1.17138965e-04  5.28033629e-03]
relative in body [0.00111906 0.99998543 0.00528034]
angles 0.06411805637554306 0.3025425789733269
True
relative in global [-9.99944212e-01  2.34264023e-04  1.05601914e-02]
relative in body [0.00223801 0.99994174 0.01056019]
angles 0.12823587736244768 0.6050671571945385
True
relative in global [-9.99874492e-01  3.51361273e-04  1.58390842e-02]
relative in body [0.00335677 0.99986892 0.01583908]
angles 0.19235322757779336 0.9075557402014286
True
relative in global [-9.99776911e-01  4.68416824e-04  2.11165343e-02]
relative in body [0.00447523 0.99976701 0.02111653]
angles 0.2564698716501101 1.2099903461061425
True
relative in global [-9.99651497e-01  5.85416805e-04  2.63920617e-02]
relative in body [0.0055933  0.99963602 0.02639206]
angles 0.3205855742250806 1.5123530118685806
True
relative in global [-9.99498285e-01  7.02347367e-04  3.1

KeyboardInterrupt: 