In [1]:
import cv2
import pykep
import numpy as np
import imutils
import math

Image tools

In [2]:
def debris_in_pixels(physical_size, distance, alpha=np.pi/6, beta=np.pi/6, dimensions = (1080, 1980)):
    """
    Returns how many pixels the object at a given distance should take up
    :param physical_size: The size of the object
    :param distance: Distance between the target and observer
    :param alpha: horizontal FOV. Radians
    :param beta: vertical FOV. Radians
    :param dimensions: the pixel dimensions of the observer camera used
    """
    
    len_x = 2*np.tan(alpha)*distance
    len_y = 2*np.tan(beta)*distance
    
    px_per_length_cols =  dimensions[0]/len_x
    px_per_length_rows =  dimensions[1]/len_y
    new_shape = math.ceil(physical_size[0] * px_per_length_cols), math.ceil(physical_size[1] * px_per_length_rows)
    # think about the rounding here
    return new_shape


def resize(original_image, physical_size, distance):
    """
    Resize the image based on the physical size of the target object and the relative distance between 
    target object and observer
    :param physical_size: The size of the object in km
    :param distance: Distance between the target and observer planes, the z coordinate of the relative vector
    """
    width, height = debris_in_pixels(physical_size, distance)
    if width == 0 and height ==0:
        return False  # can't resize, object too small
    else:
        return cv2.resize(original_image, (width, height), interpolation=cv2.INTER_AREA)

In [24]:
def roi_in_frame(left_corner, object_size, frame):
    """
    Return the part of the ROI that is in the frame.
    :left_corner: the coordinates of the left corner of the object in px.
    :object_size: size of the object in pixels in CV2 coordinates (columns, rows)
    """
    frame_size = frame.shape
    ROI = [[left_corner[0], left_corner[0] + object_size[0]],[left_corner[1], left_corner[1] + object_size[1]]]
    
    if left_corner[0] + object_size[0] > frame_size[0]:
        print("1")
        # outside the right bounding edge
        ROI[0] = [left_corner[0], frame_size[0]]
    if left_corner[0] < 0:
        print("2")
        # outside the left bounding edge
        ROI[0] = [0, left_corner[0] + object_size[0]]

    if left_corner[1] + object_size[1] > frame_size[1]:
        print("3")
        # outside the bottom bounding edge
        ROI[1] = [left_corner[1], frame_size[1]]
    if left_corner[1] < 0:
        print("4")
        # outside the upper bounding edge
        ROI[1] = [0, left_corner[1] + object_size[1]]

    return frame[ROI[0][0]:ROI[0][1], ROI[1][0]:ROI[1][1]]


def obj_in_frame(left_corner, frame, img):
    image_size = img.shape
    frame_size = frame.shape
    ROI = [[0,image_size[0]],[0,image_size[1]]]  # the whole image of the object
    if left_corner[0] + image_size[0] > frame_size[0]:
        # outside the right bounding edge
        ROI[0] = [0, frame_size[0] - left_corner[0]]
    if left_corner[0] < 0:
        # outside the left bounding edge
        ROI[0] = [-left_corner[0], image_size[0]]

    if left_corner[1] + image_size[1] > frame_size[1]:
        # outside the bottom bounding edge
        ROI[1] = [0, frame_size[1] - left_corner[1]]
    if left_corner[1] < 0:
        # outside the upper bounding edge
        ROI[1] = [-left_corner[1], image_size[1]]

    return img[ROI[0][0]:ROI[0][1], ROI[1][0]:ROI[1][1]] 

In [4]:
def create_mask(img):
    return np.zeros(img.shape[:2], dtype="uint8")

Orbital Mechanics

In [5]:
def propagate_based_on_vector(r,v, t):
    rf, vf = pykep.propagate_lagrangian(r0 = r, v0 = v, tof = t,mu = 398600)
    return np.array(rf), np.array(vf)

def propagate_based_on_elements(elements, t, kepler=True):
    r, v = pykep.par2ic(elements, mu=398600)
    rf,vf = pykep.propagate_lagrangian(r0 = r, v0 = v, tof = t,mu = 398600)
    if kepler == False:  # return vectors
        return np.array(rf),np.array(vf)
    if kepler == True:  # return kepler elements
        return pykep.ic2par(rf,vf,mu = 398600)

Utility

In [6]:
def delete_white_background(img, write=False):
    """
    Takes the images of Debris that I made in paint.
    Inverts the colours and deletes the white background.
    """
    img = np.invert(img)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    _, alpha = cv2.threshold(gray, 240, 255, cv2.THRESH_BINARY)
    
    # Using cv2.split() to split channels 
    # of coloured image
    b, g, r = cv2.split(img)

    # Making list of Red, Green, Blue
    # Channels and alpha
    rgba = [b,g,r, alpha]

    # Using cv2.merge() to merge rgba
    # into a coloured/multi-channeled image
    dst = cv2.merge(rgba,3)
    print("dst shape", dst.shape)

    # Writing and saving to a new image
    if write is True:
        cv2.imwrite("debris/deb.png", dst)
    return dst        

FOV

In [7]:
# Checks if a matrix is a valid rotation matrix.
def isRotationMatrix(R) :
    Rt = np.transpose(R)
    shouldBeIdentity = np.dot(Rt, R)
    I = np.identity(3, dtype = R.dtype)
    n = np.linalg.norm(I - shouldBeIdentity)
    return n < 1e-6
 
# Calculates rotation matrix to euler angles
# The result is the same as MATLAB except the order
# of the euler angles ( x and z are swapped ).
def rotationMatrixToEulerAngles(R) :
 
    assert(isRotationMatrix(R))
 
    sy = math.sqrt(R[0,0] * R[0,0] +  R[1,0] * R[1,0])
 
    singular = sy < 1e-6
 
    if  not singular :
        x = math.atan2(R[2,1] , R[2,2])
        y = math.atan2(-R[2,0], sy)
        z = math.atan2(R[1,0], R[0,0])
    else :
        x = math.atan2(-R[1,2], R[1,1])
        y = math.atan2(-R[2,0], sy)
        z = 0
 
    return np.array([x, y, z])

In [8]:
def to_body_axis(vector, r, v):
    """
    Calculates the rotation matrix and applies it. Returns the converted vector.
    r and v are used to calculate the rotation matrix and vector is the vector to be 
    rotated.
    """
    unit_r = r/np.linalg.norm(r)
    unit_v = v/np.linalg.norm(v)

    R = np.array([[unit_v[0], -unit_r[0], unit_r[1]*unit_v[2] - unit_v[1]*unit_r[2]],
                [unit_v[1], -unit_r[1], unit_v[0]*unit_r[2] - unit_r[0]*unit_v[2]],
                [unit_v[2], -unit_r[2], unit_r[0]*unit_v[1] - unit_v[0]*unit_r[1]]])
    R = R.transpose()
    
    return R.dot(vector)

In [9]:
vec = [1,0,0]
r = [1,1,0]
v = [0,0,1]
to_body_axis(vec, r, v)

array([ 0.        , -0.70710678,  0.70710678])

In [31]:
def angle_between(r1,r2):
    """
    Calculate the angle between two vectors
    """
    unit_1 = r1/np.linalg.norm(r1)
    unit_2 = r2/np.linalg.norm(r2)
    return np.arccos(np.dot(unit_1,unit_2))

def behind_earth(r1, r2, R=6371):
    """
    Checks if the target is between the Earth and observer based on 
    a line segment intersecting the sphere.
    Returns true if the target is behind the Earth.
    :param r1: observer
    :param r2: target
    """
    if angle_between(r1,r2) < np.pi/2:  
        return False  # does not intersect
    
    phi = np.arccos(np.dot(r1, r2-r1)/(np.linalg.norm(r1)*np.linalg.norm(r2-r1)))
    H = np.linalg.norm(r1)*np.sin(phi)
    
    if H <= R:
        return True  # intersects
    if H > R:
        return False  # does not intersect

def in_FOV(r1, v1, r2, max_vertical=np.radians(60), max_horisontal=np.radians(60)):
    """
    Checks if the observer should be able to see the target.
    1 for observer. 2 for target.
    Returns True if yes
    """

    rel = r2 - r1
    
    if behind_earth(r1,r2) is True:
        print("failed cause earth")
        return False
    
    rel_unit = (rel)/np.linalg.norm(rel)
    print("relative in global", rel_unit)
    rel_unit = to_body_axis(rel_unit, r1, v1) 
    print("relative in body", rel_unit)
    if rel_unit[1] < 0:
        print("failed cause y")
        return False

    horisontal_angle = abs(np.arctan(rel_unit[0]/rel_unit[1]))  # in the xy plane 
    vertical_angle = abs(np.arctan(rel_unit[2]/rel_unit[1]))  # in yz plane
    print("angles", np.degrees(horisontal_angle),np.degrees(vertical_angle))
    if horisontal_angle <= max_horisontal and vertical_angle <= max_vertical:
        return True
    else:
        print("failed cause angles")
        return False

In [11]:
r1 = np.array([7300,0,0])
r2 = np.array([7200,0,0])
behind_earth(r1, r2)

False

In [29]:
def get_distance(r1, v1, r2):
    rel = r2 - r1
    rel = to_body_axis(rel, r1, v1)
    distance = rel[1]  # y axis is pointed towards Earth
    return distance

def to_pixels(r,distance, cols=1980, rows=1080, alpha=np.pi / 6, beta=np.pi / 6,):
    """
    Converts physical location to pixels.
    """
    len_x = 2*np.tan(alpha)*distance
    len_y = 2*np.tan(beta)*distance
    px_per_length_cols =  cols/len_x
    px_per_length_rows =  rows/len_y
    return math.ceil(r[0]*px_per_length_cols)+cols, math.ceil(r[2]*px_per_length_rows)+rows


Initialisation

In [36]:
elements_sat = [7350,0.0,np.radians(0),np.radians(289.042),np.radians(293.776),np.radians(66.230)]
elements_deb = [7133.8,0.0043,np.radians(98.289),np.radians(49.866),np.radians(356.768),np.radians(149.512)]

In [37]:
vs = "Earth\sized_Earth_slowed.avi"
img_path = "debris\deb1.png"

In [38]:
object_og = cv2.imread(img_path)
#print(object_og.shape)
#object_og = delete_white_background(object_og, write=False)
#print(object_og.shape)
distance = 1000
object_resized = resize(object_og, (10,10), distance)
cv2.imshow("resized", object_resized)
cv2.waitKey(0)

32

: 

In [18]:
cap = cv2.VideoCapture(vs)  # open the video file
frame_width = int(cap.get(3))
frame_height = int(cap.get(4))
out = cv2.VideoWriter('Earth_ball.avi', cv2.VideoWriter_fourcc('M', 'J', 'P', 'G'), 30, (frame_width, frame_height))
t = 0
if cap.isOpened() is False:
    print("Error opening video file")

Body

In [35]:
while cap.isOpened():
    ret0, frame = cap.read()
    if ret0 is True:
        rO, vO = propagate_based_on_elements(elements_sat, t, kepler=False)
        rT, vT = propagate_based_on_elements(elements_deb, t, kepler=False)
        t+=1  # move ahead by one second
        if in_FOV(rO, vO, rT) is True:
            rel = rT - rO
            distance = np.linalg.norm(rel)
            print("distance", distance)
            object_resized = resize(object_og, (500,500), distance)  # size of target in pixels
            if object_resized is not False:
                rel = to_body_axis(rel, rO, vO)
                print(rel)
                left_corner = to_pixels(rel, distance)  # location of target in the frame
                print("left corner", left_corner)
                print("object resized", object_resized.shape)
                print("frame", frame.shape)
                roi = roi_in_frame(left_corner, object_resized.shape, frame)
                print("roi shape", roi.shape)
                # create mask and inverse mask
                object_in_frame = obj_in_frame(left_corner,frame,object_resized)
                mask = create_mask(object_in_frame)
                mask_inv = cv2.bitwise_not(mask)
                print("mask shape", mask.shape)
                #cv2.imshow("mask", mask)
                #cv2.imshow("inverse mask", mask_inv)
                frame_bg = cv2.bitwise_and(roi, roi, mask=mask_inv)
                object_fg = cv2.bitwise_and(object_in_frame, object_in_frame, mask=mask)
                print("object_fg", object_fg.shape)
                print("frame_bg", frame_bg.shape)
                #cv2.imshow("frame background", frame_bg)
                #cv2.imshow("object foreground", object_fg)
                dst = cv2.add(frame_bg, object_fg)
                cv2.imshow("dst", dst)
                frame[left_corner[0]:roi.shape[0]+left_corner[0],left_corner[1]:roi.shape[1]+left_corner[1]] = dst
                
                cv2.imshow("Earth with ball", frame)
                cv2.waitKey(0)
        out.write(frame)
    else:
        break

out.release()
cap.release()
cv2.destroyAllWindows()

relative in global [-0.80745625  0.26797291  0.52555202]
relative in body [-0.67005176  0.52423822  0.52555202]
angles 51.960918770384616 45.07170491289264
distance 7331.046522065066
[-4912.18062222  3843.2147901   3852.84631416]
left corner (832, 1572)
object resized (24, 13, 3)
frame (1080, 1920, 3)
roi shape (24, 13, 3)
mask shape (24, 13)
object_fg (24, 13, 3)
frame_bg (24, 13, 3)
relative in global [-0.80844599  0.26715553  0.52444543]
relative in body [-0.6707338   0.52447418  0.52444543]
angles 51.976694541340876 44.99842967480475
distance 7334.734839894303
[-4919.65456809  3846.87901819  3846.66815849]
left corner (830, 1571)
object resized (24, 13, 3)
frame (1080, 1920, 3)
roi shape (24, 13, 3)
mask shape (24, 13)
object_fg (24, 13, 3)
frame_bg (24, 13, 3)
relative in global [-0.80943241  0.26633827  0.52333842]
relative in body [-0.67141287  0.52471102  0.52333842]
angles 51.992275293763676 44.924961884427326
distance 7338.436555454388
[-4927.12075335  3850.55850204  3840.485