#Method 1

In [3]:
from imutils.video import VideoStream
import imutils
import cv2
import numpy as np
import copy
from matplotlib import pyplot as plt
import pandas as pd

In [2]:
def init_data(point,t):
    data = {}
    data["start time"] = t
    data["points"] = [point]
    data["last_slope"] = None
    return data

def same_point(point1, point2):
    if point1 == point2:
        return True
    if point1[0] == point2[0] and point1[1] != point2[1]:
        return None  # corresponds to infinite slope
    else:
        return False

In [3]:
def get_slope(point1, point2):
    return (point1[1]-point2[1])/(point1[0]-point2[0])

def proximity(point1, point2, R=50):
    if (point1[0] - point2[0])**2 + (point1[1] - point2[1])**2 <= R**2:
        return True
    else:
        return False

In [4]:
def update_line(point, data):
    """
    Returns the updated line (data) with all the points and last slope. If the point does not lie within this 
    "band" then returns the unchanged line (data)
    """
    list_of_previous_points = data["points"]
    last_slope = data["last_slope"]
    last_point = list_of_previous_points[-1]
    initial_point = list_of_previous_points[0]

    if proximity(point, last_point) is True:  # point is in close proximity
        if len(list_of_previous_points) >= 2:
            if same_point(point, last_point) is False:
                    slope_to_test = get_slope(point, last_point)
                    if same_point(point, initial_point) is False:
                        slope_init = get_slope(point, initial_point)
                        if check_slope(slope_init, last_slope, slope_to_test) is True:
                            print("passed constraints")
                            list_of_previous_points.append(point)
                            # update dict
                            data["points"] = list_of_previous_points
                            data["last_slope"] = slope_to_test

            if same_point(point, last_point) is True:
                list_of_previous_points.append(point)
                data["points"] = list_of_previous_points

        if len(list_of_previous_points) == 1:
            if same_point(point, initial_point) is False:
                slope = (point[1]-initial_point[1])/(point[0]-initial_point[0])
                # update dict
                data["last_slope"] = slope
                
            list_of_previous_points.append(point)
            data["points"] = list_of_previous_points
    
    return data
            
        
def check_slope(slope1, slope2, slope3, slope_error=2):
    """
    checks if slope3 is similar to slopes 2 and 3.   
    """
    if slope2 is None:
        if abs(slope1 - slope3) <= slope_error:
            return True
    if slope2 is not None:
        if abs(slope1 - slope3) <= slope_error and abs(slope2 - slope3) <= slope_error:
            return True
    else:
        return False

In [5]:
def check_for_lines(datas,point, t):
    if bool(datas) is False:  # no data points yet
        data = init_data(point,t)
        datas.append(data)
    else:
        count = 0  # used to keep in memory the amount of times a point was part of a line
        for i in range(len(datas)):
            line = copy.deepcopy(datas[i])
            new_line = datas[i]
            update_line(point,new_line)
            if line != new_line:
                count += 1
                
        if count == 0: # the point didn't correspond to any existing line
            data = init_data(point,t)
            datas.append(data)  # create a new line

    return datas

In [7]:
def to_unit_vector(point, width=1080, height=1980 , AOV=np.radians(44.4)):
    """
    y points through the screen and x points right (CCW motion)
    """
    distance_to_screen = (width**2+height**2)**0.5/(4*np.tan(AOV))
    vector = np.array((point[0]-width/2, distance_to_screen, point[1]-height/2))
    #print("vector in px", vector)
    return vector/np.linalg.norm(vector)

to_unit_vector([0,0])

array([-0.42647775,  0.45473823, -0.78187587])

In [8]:
to_unit_vector([1080/2, 1980/2])

array([0., 1., 0.])

In [7]:
video_location = 'Earth_ball.avi'
vs = cv2.VideoCapture(video_location)

In [8]:
# initialize the first frame in the video stream
avg = None
# initialise data on debris lines
datas = []

In [9]:
#main body
accumulated_thresh = np.zeros((1080,1920))
while True:
    frame = vs.read()
    frame = frame[1]
    text = "unoccupied"
    
    # if the frame could not be grabbed, then we have reached the end
    # of the video
    if frame is None:
        break
    
    # resize the frame, convert it to grayscale, and blur it
    
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    gray = cv2.GaussianBlur(gray, (3, 3), 0)

    # if the first frame is None, initialize it
    if avg is None:
        avg = gray.copy().astype("float")
        continue

    # compute the absolute difference between the current frame and
    # first frame
    cv2.accumulateWeighted(gray, avg, 0.5)
    frameDelta = cv2.absdiff(gray, cv2.convertScaleAbs(avg))
    thresh = cv2.threshold(frameDelta, 25, 255, cv2.THRESH_BINARY)[1]

    # dilate the thresholded image to fill in holes, then find contours
    # on thresholded image
    thresh = cv2.dilate(thresh, None, iterations=2)
    cnts = cv2.findContours(thresh.copy(), cv2.RETR_TREE,
    	cv2.CHAIN_APPROX_SIMPLE)
    cnts = imutils.grab_contours(cnts)
    # save the contours into an accumulated thresh image
    accumulated_thresh = cv2.accumulate(thresh, accumulated_thresh)

	# loop over the contours
    for c in cnts:
        if cv2.contourArea(c) > 200:
		# compute the bounding box for the contour, draw it on the frame,
		# and update the text
            """
            (x, y, w, h) = cv2.boundingRect(c)
            cv2.rectangle(frame, (x, y), (x + w, y + h), (0, 255, 0), 2)
            """
            ellipse = cv2.fitEllipse(c)
            cv2.ellipse(frame,ellipse,(0,255,0),2)
            text = "Occupied"
            # get the location of the centroid
            M = cv2.moments(c)
            cx = int(M['m10']/M['m00'])
            cy = int(M['m01']/M['m00'])
            print("-------------------------------")
            print([cx,cy])
            datas = check_for_lines(datas, [cx,cy])

    
    # draw the text and timestamp on the frame
    #cv2.putText(frame, "Room Status: {}".format(text), (10, 20),
    #cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 2)

    #cv2.putText(frame, datetime.datetime.now().strftime("%A %d %B %Y %I:%M:%S%p"),
    #(10, frame.shape[0] - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.35, (0, 0, 255), 1)

	# show the frame and record if the user presses a key
    """
    cv2.imshow("Satellite Feed", frame)
    cv2.imshow("accumulated", accumulated_thresh)
    cv2.imshow("Thresh", thresh)
    cv2.imshow("Frame Delta", frameDelta)
    cv2.waitKey(0)
    """
    
cv2.destroyAllWindows()

-------------------------------
[994, 539]
-------------------------------
[994, 539]
-------------------------------
[999, 539]
passed constraints
-------------------------------
[1009, 538]
passed constraints
-------------------------------
[1018, 537]
passed constraints
-------------------------------
[1027, 536]
passed constraints
-------------------------------
[1036, 535]
passed constraints
-------------------------------
[1045, 533]
passed constraints
-------------------------------
[1053, 532]
passed constraints
-------------------------------
[1061, 531]
passed constraints
-------------------------------
[1069, 531]
passed constraints
-------------------------------
[1078, 530]
passed constraints
-------------------------------
[1087, 529]
passed constraints
-------------------------------
[1096, 528]
passed constraints
-------------------------------
[1105, 527]
passed constraints
-------------------------------
[1114, 526]
passed constraints
-------------------------------
[

Data analysis

In [10]:
datas_copy = copy.deepcopy(datas)
datas_new = copy.deepcopy(datas)

In [11]:
for dict in datas_copy:
    if len(dict["points"]) <= 15:
        print(len(dict["points"]))
        print("-----------------")
        print(dict)
        datas_new.remove(dict)

2
-----------------
{'points': [[776, 940], [783, 942]], 'last_slope': 0.2857142857142857}
11
-----------------
{'points': [[897, 769], [902, 772], [906, 771], [908, 770], [915, 771], [918, 769], [920, 770], [925, 770], [935, 769], [941, 768], [948, 768]], 'last_slope': 0.0}
7
-----------------
{'points': [[660, 768], [632, 732], [662, 769], [632, 730], [645, 744], [654, 754], [615, 757]], 'last_slope': -0.07692307692307693}
6
-----------------
{'points': [[700, 685], [709, 659], [718, 642], [723, 623], [728, 606], [730, 601]], 'last_slope': -2.5}
4
-----------------
{'points': [[903, 654], [906, 653], [913, 663], [887, 621]], 'last_slope': 1.6153846153846154}
15
-----------------
{'points': [[597, 606], [597, 600], [608, 619], [619, 620], [627, 618], [607, 599], [629, 616], [631, 617], [610, 597], [633, 615], [613, 598], [625, 588], [621, 595], [620, 597], [633, 597]], 'last_slope': 0.0}
7
-----------------
{'points': [[673, 434], [645, 398], [675, 434], [677, 435], [679, 435], [681, 

In [19]:
set_of_meas = []
for dict1 in datas_new:
    line = []
    line.append(dict1["start time"])
    for point in dict1["points"]:
        new_point = to_unit_vector(point)
        line.append(new_point)
    set_of_meas.append(line)

[ 0.52739271 -0.52390774  0.66886292]
[ 0.52739271 -0.52390774  0.66886292]
[ 0.53156623 -0.52230146  0.66681221]
[ 0.53947579 -0.51992123  0.6623049 ]
[ 0.54643059 -0.51785158  0.65821224]
[ 0.55326227 -0.51577221  0.65412528]
[ 0.55997242 -0.51368438  0.65004558]
[ 0.56623742 -0.51241683  0.64560373]
[ 0.57195964 -0.51063843  0.64195838]
[ 0.57758968 -0.5088554   0.63832308]
[ 0.58345459 -0.50624888  0.63505339]
[ 0.58961955 -0.50413568  0.63102774]
[ 0.59567255 -0.50202019  0.6270167 ]
[ 0.60161532 -0.49990338  0.62302137]
[ 0.6074496  -0.49778613  0.61904276]
[ 0.61317715 -0.49566933  0.61508186]
[ 0.61879971 -0.4935538   0.61113956]
[ 0.62496194 -0.49111681  0.60681698]
[ 0.63036854 -0.48900682  0.60291611]
[ 0.63567558 -0.48690044  0.59903633]
[ 0.64027507 -0.48511956  0.59557271]
[ 0.64479866 -0.4833419   0.59212777]
[ 0.64983844 -0.48124828  0.58831122]
[ 0.65478519 -0.47916064  0.58451812]
[ 0.6596406  -0.47707952  0.58074901]
[ 0.66408998 -0.4757809   0.5767296 ]
[ 0.66876893

In [15]:
df = pd.DataFrame(set_of_meas)
df.to_csv('data/measurments.csv', index=False)

Visualisation

In [100]:
i = 0

In [110]:
print(i)
points = datas_new[i]["points"]
print(points)
plt.plot(points[0], points[1])
plt.show()
i +=1

9


IndexError: list index out of range

#Method 2

In [9]:
# KNN
backSub = cv2.createBackgroundSubtractorKNN()

In [10]:
# MOG2
backSub = cv2.createBackgroundSubtractorMOG2()

In [11]:
while True:
    ret, frame = vs.read()
    if frame is None:
        break

    fgMask = backSub.apply(frame)

    thresh = cv2.dilate(fgMask, None, iterations=2)  # makes bright regions grow
    cnts = cv2.findContours(fgMask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    cnts = imutils.grab_contours(cnts)

    # loop over the contours
    for c in cnts:
        if cv2.contourArea(c) > 200:
            # compute the bounding box for the contour, draw it on the frame
            (x, y, w, h) = cv2.boundingRect(c)
            cv2.rectangle(frame, (x, y), (x + w, y + h), (0, 255, 0), 2)
            text = "Occupied"

    cv2.rectangle(frame, (10, 2), (100, 20), (255, 255, 255), 1)
   
    cv2.imshow('Frame', frame)
    cv2.imshow('Thresh', thresh)
    cv2.imshow('FG Mask', fgMask)

    cv2.waitKey(0)
    
cv2.destroyAllWindows()